[omniwm]
src.github = "BarutSRB/OmniWM"
fetch.url = "https://github.com/BarutSRB/OmniWM/releases/download/$ver/OmniWM-$ver.zip"

# [scroll-reverser]
# src.github_tag = "pilotmoon/Scroll-Reverser"
# src.prefix = "v"
# fetch.url = "https://github.com/pilotmoon/Scroll-Reverser/releases/download/v$ver/ScrollReverser-$ver.zip"
