- name: nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
  args:
    creates: "~/.config/nvm/nvm.sh"

- name: nodejs install
  shell:  \. "${HOME}/.config/nvm/nvm.sh" && nvm install --lts --latest-npm && nvm alias default 'lts/*'
