- name: Make user systemed dir
  file:
    path: ~/.config/systemd/user
    state: directory

- name: Link xkeysnail systemctl
  file:
    src: "{{ role_path }}/files/xkeysnail.service"
    dest: ~/.config/systemd/user/xkeysnail.service
    state: link

- name: Link xkeysnail
  file:
    src: "{{ role_path }}/files/xkeysnail"
    dest: ~/.config/xkeysnail
    state: link
