# xdg config
[xdg-utils]
type = "basic"
common = [{ name = "xdg-utils", method = "nix-hm" }]

# build package
[nix]
type = "basic"
common = [
  { name = "nix", method = "script", function = "setup_nix" },
  { name = "nix-index", method = "nix-hm" },
  { name = "nvfetcher", method = "nix-hm" },
]
[direnv]
type = "basic"
common = [{ name = "direnv", method = "nix-hm" }]

[gcc]
type = "basic"
nixos = [{ name = "gcc", method = "nix" }]

[gnumake]
type = "basic"
nixos = [{ name = "gnumake", method = "nix" }]

# CLI command packages
[bash]
type = "basic"
common = [{ name = "bash", method = "nix" }]

[zsh]
type = "basic"
arch = [{ name = "zsh", method = "pacman" }]
ubuntu = [{ name = "zsh", method = "apt" }]
common = [{ name = "zsh", method = "nix-hm" }]

[coreutils]
type = "basic"
arch = [{ name = "coreutils", method = "pacman" }]
darwin = [{ name = "coreutils", method = "nix-hm" }]
ubuntu = [{ name = "coreutils", method = "apt" }]
nixos = [{ name = "coreutils", method = "nix" }]

[findutils]
type = "basic"
common = [{ name = "findutils", method = "nix" }]

[grep]
type = "basic"
common = [{ name = "gnugrep", method = "nix" }]

[sed]
type = "basic"
common = [{ name = "gnused", method = "nix" }]

[gawk]
type = "basic"
common = [{ name = "gawk", method = "nix" }]

[less]
type = "basic"
common = [
  { name = "less", method = "nix-hm" },
  { name = "lesspipe", method = "nix-hm" },
]
nixos = [{ name = "less", method = "nix" }]

[tree]
type = "basic"
common = [{ name = "tree", method = "nix" }]

[rsync]
type = "basic"
common = [{ name = "rsync", method = "nix" }]

[yj]
type = "basic"
common = [{ name = "yj", method = "nix-hm" }]

[jq]
type = "basic"
common = [{ name = "jq", method = "nix-hm" }]

[fzf]
type = "basic"
common = [{ name = "fzf", method = "nix-hm" }]

[duf]
type = "basic"
common = [{ name = "duf", method = "nix-hm" }]

[fastfetch]
type = "basic"
common = [{ name = "fastfetch", method = "nix-hm" }]

[zip]
type = "basic"
common = [
  { name = "zip", method = "nix-hm" },
  { name = "unzip", method = "nix-hm" },
]

[unarchiver]
type = "basic"
common = [{ name = "unar", method = "nix" }]

[gtrash]
type = "basic"
common = [{ name = "gtrash", method = "nix-hm" }]

[tmux]
type = "basic"
common = [
  { name = "tmux", method = "nix-hm" },
  { name = "tmux-mem-cpu-load", method = "nix-hm" },
]

[git]
type = "basic"
common = [
  { name = "git", method = "nix-hm" },
  { name = "pre-commit", method = "nix-hm" },
  { name = "gitleaks", method = "nix-hm" },
]

[sheldon]
type = "basic"
common = [{ name = "sheldon", method = "nix-hm" }]

[procs]
type = "basic"
common = [{ name = "procs", method = "nix-hm" }]

[bat]
type = "basic"
common = [{ name = "bat", method = "nix-hm" }]

[fd]
type = "basic"
common = [{ name = "fd", method = "nix-hm" }]

[sd]
type = "basic"
common = [{ name = "sd", method = "nix-hm" }]

[ripgrep]
type = "basic"
common = [{ name = "ripgrep", method = "nix-hm" }]

[delta]
type = "basic"
common = [{ name = "delta", method = "nix-hm" }]

[lsd]
type = "basic"
common = [{ name = "lsd", method = "nix-hm" }]

[dust]
type = "basic"
common = [{ name = "dust", method = "nix-hm" }]

[csview]
type = "basic"
common = [{ name = "csview", method = "nix-hm" }]

[zoxide]
type = "basic"
common = [{ name = "zoxide", method = "nix-hm" }]

[navi]
type = "basic"
common = [{ name = "navi", method = "nix-hm" }]

[lazygit]
type = "basic"
common = [{ name = "lazygit", method = "nix-hm" }]

[ssh]
type = "basic"
common = [{ name = "ssh_config", method = "nix-hm" }]

[drill]
type = "basic"
common = [{ name = "ldns", method = "nix-hm" }]

## toml
[taplo]
type = "basic"
common = [{ name = "taplo", method = "nix-hm" }]

## for html/css/json/eslint
[vscode-langservers-extracted]
type = "basic"
common = [{ name = "vscode-langservers-extracted", method = "nix-hm" }]

## for yaml
[yaml-language-server]
type = "basic"
common = [{ name = "yaml-language-server", method = "nix-hm" }]

## for markdown
[marksman]
type = "basic"
common = [{ name = "marksman", method = "nix-hm" }]

## package mananger for arch
[paru]
type = "basic"
arch = [{ name = "paru", method = "nix-hm" }]

## security
[openssl]
type = "basic"
arch = [{ name = "openssl", method = "pacman" }]
darwin = [{ name = "openssl", method = "nix-hm" }]
ubuntu = [{ name = "openssl", method = "apt" }]

[gnupg]
type = "basic"
arch = [{ name = "gnupg", method = "pacman" }]
ubuntu = [{ name = "gnupg", method = "apt" }]
common = [{ name = "gnupg", method = "nix-hm" }]

[sops]
type = "basic"
common = [
  { name = "sops", method = "nix-hm" },
  { name = "age", method = "nix-hm" }
]

[macos-security]
type = "basic"
darwin = [
  { name = "pinentry_mac", method = "nix-hm" },
  { name = "pam-reattach", method = "nix-hm" },
]

## downloader
[wget]
type = "basic"
common = [{ name = "wget", method = "nix-hm" }]

[curl]
type = "basic"
common = [{ name = "curl", method = "nix-hm" }]

[aria2]
type = "basic"
common = [{ name = "aria", method = "nix-hm" }]

## top series
[htop]
type = "basic"
common = [{ name = "htop", method = "nix-hm" }]

[bottom]
type = "basic"
common = [{ name = "bottom", method = "nix-hm" }]

[iotop]
type = "basic"
linux = [{ name = "iotop", method = "nix-hm" }]

## Editor
[vim]
type = "basic"
common = [{ name = "vim", method = "nix-hm" }]

[emacs-basic]
type = "basic"
common = [
  { name = "emacs", method = "nix-hm" },
  { name = "hunspell", method = "nix" },
  { name = "hunspellDicts.en_US", method = "nix" },
  { name = "enchant", method = "nix-hm" },
  { name = "emacs-lsp-booster", method = "nix-hm" },
  { name = "pandoc", method = "nix-hm" },
  { name = "cmigemo", method = "nix-hm" },
]

[emacs-gui]
type = "gui"
linux = [
  { name = "isync", method = "nix-hm" },
  { name = "msmtp", method = "nix-hm" },
  { name = "mu", method = "nix-hm" },
  { name = "goimapnotify", method = "nix-hm" },
]
darwin = [
  { name = "pngpaste", method = "nix-hm" },
]

## repository management
[ghq]
type = "basic"
common = [{ name = "ghq", method = "nix-hm" }]

# development packages
## SSO
[saml2aws]
type = "dev"
common = [{ name = "saml2aws", method = "nix-hm" }]

## shell script
[shellcheck]
type = "dev"
common = [{ name = "shellcheck-minimal", method = "nix-hm" }]

## for nix
[nixd]
type = "dev"
common = [{ name = "nixd", method = "nix-hm" }]

[nixfmt-rfc-style]
type = "dev"
common = [{ name = "nixfmt-rfc-style", method = "nix-hm" }]

## for python
[python]
type = "dev"
common = [{ name = "python", method = "nix-hm" }]

[ruff]
type = "dev"
common = [{ name = "ruff", method = "nix-hm" }]

[pyright]
type = "dev"
common = [{ name = "pyright", method = "nix-hm" }]

### for python build
ubuntu = [
  { name = "build-essential", method = "apt" },
  { name = "libbz2-dev", method = "apt" },
  { name = "libdb-dev", method = "apt" },
  { name = "libreadline-dev", method = "apt" },
  { name = "libffi-dev", method = "apt" },
  { name = "libgdbm-dev", method = "apt" },
  { name = "liblzma-dev", method = "apt" },
  { name = "libncursesw5-dev", method = "apt" },
  { name = "libsqlite3-dev", method = "apt" },
  { name = "libssl-dev", method = "apt" },
  { name = "zlib1g-dev", method = "apt" },
  { name = "uuid-dev", method = "apt" },
]

[uv]
type = "dev"
common = [{ name = "uv", method = "nix-hm" }]

## for bash
[bash-language-server]
type = "dev"
common = [{ name = "bash-language-server", method = "nix-hm" }]

## for lua
[lua-lsp]
type = "dev"
common = [{ name = "lua53Packages.lua-lsp", method = "nix-hm" }]

## for typescript
[typescript-language-server]
type = "dev"
common = [{ name = "typescript-language-server", method = "nix-hm" }]

[typescript]
type = "dev"
common = [{ name = "typescript", method = "nix-hm" }]

## google cloud sdk
[google-cloud-sdk]
type = "dev"
common = [{ name = "google-cloud-sdk", method = "nix-hm" }]

## aws cli
[awscli2]
type = "dev"
common = [{ name = "awscli2", method = "nix-hm" }]

## config for docker
[docker-conf]
type = "dev"
linux = [{ name = "docker-conf", method = "nix-hm" }]

# podman for build/push
[podman]
type = "dev"
linux = [{ name = "podman", method = "nix-hm" }]

## kubernetes
[kubectl]
type = "dev"
common = [{ name = "kubectl", method = "nix-hm" }]
[k9s]
type = "dev"
common = [{ name = "k9s", method = "nix-hm" }]
[flux]
type = "dev"
common = [{ name = "fluxcd", method = "nix-hm" }]

# gui packages
## tex
[latex]
type = "gui"
common = [{ name = "texliveMedium", method = "nix-hm" }]

## communication tools
[slack]
type = "gui"
darwin = [{ name = "slack", method = "cask" }]
linux = [{ name = "slack", method = "nix-hm" }]


[discord]
type = "gui"
common = [{ name = "discord", method = "nix-hm" }]

[zoom]
type = "gui"
darwin = [{ name = "zoom", method = "cask" }]
linux = [{ name = "zoom-us", method = "nix-hm" }]

### macos only
[MeetingBar]
type = "gui"
darwin = [{ name = "meetingbar", method = "nix-hm" }]

## browser
[vivaldi]
type = "gui"
darwin = [{ name = "vivaldi", method = "cask" }]
linux = [{ name = "vivaldi", method = "nix-hm" }]

### for keymap
[google-chrome]
type = "gui"
common = [{ name = "google-chrome", method = "nix-hm" }]

### sub browser
[firefox]
type = "gui"
linux = [{ name = "firefox", method = "nix-hm" }]

## media
[vlc]
type = "gui"
common = [{ name = "vlc", method = "nix-hm" }]
linux = [
  { name = "libdvdread", method = "nix-hm" },
  { name = "libdvdnav", method = "nix-hm" },
  { name = "libdvdcss", method = "nix-hm" },
]

## research
[zotero]
type = "gui"
common = [{ name = "zotero", method = "nix-hm" }]

[anki]
type = "gui"
common = [{ name = "anki-bin", method = "nix-hm" }]

## terminal emulator
[wezterm]
type = "gui"
common = [{ name = "wezterm", method = "nix-hm" }]

## cloud storage
[nextcloud-client]
type = "gui"
darwin = [{ name = "nextcloud", method = "cask" }]
linux = [{ name = "nextcloud-client", method = "nix-hm" }]

[google-drive]
type = "gui"
darwin = [{ name = "google-drive", method = "cask" }]

## libreoffice
[libreoffice]
type = "gui"
linux = [{ name = "libreoffice-fresh", method = "nix-hm" }]
darwin = [{ name = "libreoffice-bin", method = "nix-hm" }]

## launcher
[launcher]
type = "gui"
darwin = [{ name = "raycast", method = "nix-hm" }]
linux = [{ name = "rofi-wayland", method = "nix-hm" }]

## window manager
[hyprland]
type = "gui"
nixos = [
  { name = "hyprland", method = "nix" },
  { name = "hyprland", method = "nix-hm" },
  { name = "xdg-desktop-portal-hyprland", method = "nix" },
  { name = "waybar", method = "nix-hm" },
  { name = "mako", method = "nix-hm" },
  { name = "networkmanagerapplet", method = "nix-hm" },
  { name = "hyprshot", method = "nix-hm" },
  { name = "playerctl", method = "nix-hm" },
  { name = "pwvucontrol", method = "nix-hm" },
  { name = "brightnessctl", method = "nix-hm" },
  { name = "gnome-keyring", method = "nix-hm" },
  { name = "libsecret", method = "nix-hm" },
  { name = "seahorse", method = "nix-hm" },
  { name = "nord", method = "nix-hm" },
]

[aerospace]
type = "gui"
darwin = [
  { name = "aerospace", method = "nix-hm" },
  { name = "jankyborders", method = "nix-hm" },
  { name = "sketchybar", method = "nix-hm" },
  { name = "macskk", method = "cask" },
]

## gui archiver
[xarchiver]
type = "gui"
linux = [{ name = "xarchiver", method = "nix-hm" }]

## recoll
[recoll]
type = "gui"
darwin = [{ name = "recoll", method = "cask" }]
common = [{ name = "recoll", method = "nix-hm" }]

# hugo
[hugo]
type = "gui"
linux = [{ name = "hugo", method = "nix-hm" }]

## github cli
[gh]
type = "gui"
common = [{ name = "gh", method = "nix-hm" }]

## font
[font]
type = "gui"
common = [{ name = "fonts", method = "nix-hm" }]

## key remapper
[keyremap]
type = "gui"
darwin = [
  { name = "karabiner-elements", method = "cask" },
  { name = "karabiner-elements", method = "nix-hm" },
]
nixos = [{ name = "xremap", method = "nix" }]

## dvd writing
[growisofs]
type = "gui"
common = [{ name = "dvdplusrwtools", method = "nix-hm" }]

## macos only
[utils]
type = "gui"
darwin = [{ name = "appcleaner", method = "nix-hm" }]

[WireGuard]
type = "gui"
darwin = [{ name = "\"WireGuard\" = 1451685025", method = "mas" }]

[darwin]
type = "gui"
darwin = [{ name = "macos", method = "nix-hm" }]

### external monitor control
[monitorcontrol]
type = "gui"
darwin = [{ name = "monitorcontrol", method = "nix-hm" }]
