shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.git-prompt]
github = "woefe/git-prompt.zsh"
hooks.post = '''
ZSH_THEME_GIT_PROMPT_PREFIX="("''$'\Ue725 '
ZSH_THEME_GIT_PROMPT_SUFFIX=")"
ZSH_THEME_GIT_PROMPT_SEPARATOR="|"
ZSH_THEME_GIT_PROMPT_DETACHED="%{$fg_bold[cyan]%}:"
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_bold[magenta]%}"
ZSH_THEME_GIT_PROMPT_BEHIND="↓"
ZSH_THEME_GIT_PROMPT_AHEAD="↑"
ZSH_THEME_GIT_PROMPT_UNMERGED="%{$fg[red]%}✖ "
ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[green]%}● "
ZSH_THEME_GIT_PROMPT_UNSTAGED="%{$fg[red]%}✚ "
ZSH_THEME_GIT_PROMPT_UNTRACKED="…"
ZSH_THEME_GIT_PROMPT_STASHED="%{$fg[blue]%}⚑ "
ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[green]%}✔ "
'''

[plugins.zsh-autocomplete]
github = 'marlonrichert/zsh-autocomplete'
hooks.pre = 'bindkey -e'
hooks.post = '''
bindkey '\t' menu-select \"$terminfo[kcbt]\" menu-select
bindkey -M menuselect '\t' menu-complete \"$terminfo[kcbt]\" reverse-menu-complete
bindkey '^N' history-beginning-search-forward
bindkey '^P' history-beginning-search-backward

+autocomplete:recent-directories() {
  typeset -ga reply=("${(@f)$(zoxide query -l)}")
  }

() {
   local -a prefix=( '\e'{\[,O} )
   local -a up=( ${^prefix}A ) down=( ${^prefix}B )
   local key=
   for key in $up[@]; do
      bindkey "$key" history-beginning-search-backward
   done
   for key in $down[@]; do
      bindkey "$key" history-beginning-search-forward
   done
}
'''

[plugins.syntax-highlight]
github = 'z-shell/F-Sy-H'
apply = ["defer"]

[plugins.autopair]
github = "hlissner/zsh-autopair"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-abbr]
github = "olets/zsh-abbr"
apply = ["defer"]
