- name: install rust by rustup
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y

- name: auto complete
  shell: ~/.cargo/bin/rustup completions zsh > ~/.zfunc/_rustup
  args:
    creates: ~/.local/share/zsh/completion

- name: common
  include_tasks: "common.yml"
