# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  meetingbar = {
    pname = "meetingbar";
    version = "v4.11.5";
    src = fetchurl {
      url = "https://github.com/leits/MeetingBar/releases/download/v4.11.5/MeetingBar.dmg";
      sha256 = "sha256-t8PTrKLGaZOmCYuTJ0CLJVmAG5hCha2NRR7zhMhIL1A=";
    };
  };
  vlc = {
    pname = "vlc";
    version = "3.0.21";
    src = fetchurl {
      url = "https://get.videolan.org/vlc/3.0.21/macosx/vlc-3.0.21-arm64.dmg";
      sha256 = "sha256-Fd1lv2SJ2p7Gpn9VhcdMQKWJk6z/QagpWKkW3XQXgEQ=";
    };
  };
}
