#!/usr/bin/env sh
yabai -m config external_bar all:35:0

yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff3D918C
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   6

# Rules
yabai -m rule --add app="^Dictionaries$"                  manage=off
yabai -m rule --add app="^Disk Utility$"                  manage=off
yabai -m rule --add app="^System Settings$"               manage=off
yabai -m rule --add app="^Bitwarden$"                     manage=off
yabai -m rule --add app="^Karabiner-Elements$"            manage=off
yabai -m rule --add app="^Karabiner-MultitouchExtension$" manage=off
yabai -m rule --add app="^Stats$"                         manage=off
yabai -m rule --add app="^Vivaldi$" title="Bitwarden - Vivaldi"  manage=off
yabai -m rule --add title="^Emacs$"                       manage=on
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off

echo "yabai configuration loaded.."
