- name: Include var
  include_vars: pipx.yml

- name: check exist pipx command
  shell: type ~/.local/bin/pipx
  register: exist_pipx
  ignore_errors: true
  changed_when: false

- name: Install pipx
  shell: pip3 install --user pipx
  when: exist_pipx is failed

- name: Install pipx packages
  shell: ~/.local/bin/pipx install {{ item }}
  register: pipx_install
  failed_when: false
  changed_when: "'already' not in pipx_install.stdout"
  with_items: "{{ pipx.pipx_packages }}"

- name: Install jupyterlab template extention
  shell: ~/.local/bin/pipx inject jupyterlab jupyterlab_templates

