- name: Include var
  include_vars: poetry.yml

- name: Check exist poetry command
  shell: type ~/.local/bin/poetry
  register: exist_poetry
  ignore_errors: true
  changed_when: false

- name: Install poetry
  shell: curl -sSL https://install.python-poetry.org | python3 -
  when: exist_poetry is failed

- name: Update poetry
  shell: ~/.local/bin/poetry self update
  ignore_errors: true

- name: Check poetry global settings
  shell: bash -lc "~/.local/bin/poetry config --list | grep 'virtualenvs.in-project = true'"
  register: poetry_global
  ignore_errors: true
  changed_when: false

- name: Enable virtualenvs in project
  shell: ~/.local/bin/poetry config virtualenvs.in-project true
  when: poetry_global is failed

- name: Stat _poetry
  stat:
    path: "{{ poetry.completion_file }}"
  register: completion_file

- name: Enable poetry completions
  shell: ~/.local/bin/poetry completions zsh > {{ poetry.completion_file }}
  when: not completion_file.stat.exists
