- name: Include var
  include_vars: poetry.yml

- name: Check exist poetry command
  shell: type ~/.poetry/bin/poetry
  register: exist_poetry
  ignore_errors: true
  changed_when: false

- name: Install poetry
  shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | ~/.pyenv/shims/python
  when: exist_poetry is failed

- name: Check poetry global settings
  shell: bash -lc "~/.poetry/bin/poetry config --list | grep 'virtualenvs.in-project = true'"
  register: poetry_global
  ignore_errors: true
  changed_when: false

- name: Enable virtualenvs in project
  shell: ~/.poetry/bin/poetry config virtualenvs.in-project true
  when: poetry_global is failed

- name: Stat _poetry
  stat:
    path: "{{ poetry.completion_file }}"
  register: completion_file

- name: Enable poetry completions
  shell: ~/.poetry/bin/poetry completions zsh > {{ poetry.completion_file }}
  when: not completion_file.stat.exists
