- name: Stat pyenv
  stat:
    path: "{{ pyenv.install_dir }}"
  register: pyenv_dir

- name: Clone pyenv
  git:
    repo: "{{ pyenv.git_url }}"
    dest: "{{ pyenv.install_dir }}"
  when: not pyenv_dir.stat.exists

- name: Install global python
  shell: pyenv install "{{ pyenv.global_python_version }}" && pyenv global "{{ pyenv.global_python_version }}" 
