- name: Include var
  include_vars: pyenv.yml

- name: Clone pyenv
  git:
    repo: "{{ pyenv.git_url }}"
    dest: "{{ pyenv.install_dir }}"

- name: Check installed python version
  shell: bash -lc "~/.pyenv/bin/pyenv versions | grep {{ pyenv.default_python_version }}"
  register: pyenv_result
  ignore_errors: true
  changed_when: false

- name: Install default python
  shell: ~/.pyenv/bin/pyenv install {{ pyenv.default_python_version }}
  when: pyenv_result is failed
