modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
      kEY_102ND: KEY_GRAVE

keymap:
  # - name: Global
    # remap:
      # Underscore without Shift
      # RO: Shift-RO

      # SKK hack for Chrome
      #C-j: C-m

  - name: Default
    application:
      not: [Google-chrome, Slack, wezterm, Emacs]
    remap:
      # Emacs basic
      C-b: left
      C-f: right
      C-p: up
      C-n: down
      C-h: backspace
      C-m: enter

      # Emacs word
      Super-b: C-left
      Super-f: C-right

      # Emacs lines
      C-a: home # TODO: Alt-C-a
      C-e: end # TODO: Alt-C-e
      C-k: [Shift-end, backspace] # TODO: Alt-C-k

      # Alt -> Ctrl
      Super-a: C-a
      Super-z: C-z
      Super-x: C-x
      Super-c: C-c
      Super-v: C-v
      Super-w: C-w
      Super-t: C-t
      Super-l: C-l

      C-d: delete
      Super-d: C-delete

  - name: Chrome, Slack (modified from Default)
    application:
      only: [Google-chrome, Slack, Sidekick-browser]
    remap:
      # Emacs basic
      C-b: left
      C-f: right
      C-p: up
      C-n: down
      C-h: backspace

      C-m: enter
     
      # Emacs word
      Super-b: C-left
      Super-f: C-right

      # Emacs lines
      C-a: home
      C-e: end
      C-k: [Shift-end, backspace]

      # Alt -> Ctrl
      Super-a: C-a
      Super-z: C-z
      Super-x: C-x
      Super-c: C-c
      Super-v: C-v
      Super-w: C-w
      Super-t: C-t

      # Tabs
      Super-o: C-Shift-tab
      Super-p: C-tab

      C-d: delete
      Super-d: C-delete

  - name: Google Search
    application:
      only: Google-chrome
    remap:
      Super-s: C-f
      C-g: Esc
      C-s: C-g
      Super-Enter: C-Enter

  - name: Sidekick
    application:
      only: Sidekick-browser
    remap:
      Super-s: C-f
      C-g: Esc
      Super-Enter: C-Enter
      Super-f: C-1
      
      Super-1: C-1
      Super-2: C-2
      Super-3: C-3
      Super-4: C-4
      Super-5: C-5
      Super-6: C-6
      Super-7: C-7
      Super-8: C-8
      Super-9: C-9

  - name: Wezterm
    application:
      only: org.wezfurlong.wezterm
    remap:
      Super_R-v: C-Shift-v

  - name: Slack
    application:
      only: Slack
    remap:
      Super-k: C-k
      C-M-k: Shift-Alt-up
      C-M-j: Shift-Alt-down
      C-Super-m: C-Enter

      Super-1: C-1
      Super-2: C-2
      Super-3: C-3
      Super-4: C-4
      Super-5: C-5
      Super-6: C-6
      Super-7: C-7
      Super-8: C-8
      Super-9: C-9
