modmap:
  - name: Global
    remap:
      CapsLock: Ctrl_L
  - name: wezterm
    application:
      only: wezterm
    remap:
      Super_L: Alt_L

keymap:
  # - name: Global
    # remap:
      # Underscore without Shift
      # RO: Shift-RO

      # SKK hack for Chrome
      #C-j: C-m

  - name: Default (Nocturn, etc.)
    application:
      not: [Google-chrome, Slack, wezterm, Emacs]
    remap:
      # Emacs basic
      C-b: left
      C-f: right
      C-p: up
      C-n: down
      C-h: backspace
      C-m: enter

      # Emacs word
      Super-b: C-left
      Super-f: C-right

      # Emacs lines
      C-a: home # TODO: Alt-C-a
      C-e: end # TODO: Alt-C-e
      C-k: [Shift-end, backspace] # TODO: Alt-C-k

      # Alt -> Ctrl
      Super-a: C-a
      Super-z: C-z
      Super-x: C-x
      Super-c: C-c
      Super-v: C-v
      Super-w: C-w
      Super-t: C-t
      Super-l: C-l

      # actually these are vim insert mode bindings, but compatible with shell
      C-w: [C-Shift-left, delete]

      C-d: delete
      Super-d: C-delete

  - name: wezterm
    application:
      only: wezterm
    remap:
      Alt_L-space: Super-space
      Alt_L-tab: Super-tab

  - name: Chrome, Slack (modified from Default)
    application:
      only: [Google-chrome, Slack]
    remap:
      # Emacs basic
      C-b: left
      C-f: right
      C-p: up
      C-n: down
      C-h: backspace

      C-m: enter
     
      # Emacs word
      Super-b: C-left
      Super-f: C-right

      # Emacs lines
      C-a: home
      C-e: end
      C-k: [Shift-end, backspace]

      # Alt -> Ctrl
      Super-a: C-a
      Super-z: C-z
      Super-x: C-x
      Super-c: C-c
      Super-v: C-v
      Super-w: C-w
      Super-t: C-t

      # actually these are vim insert mode bindings, but compatible with shell
      C-w: [C-Shift-left, delete]

      # Tabs
      Super-o: C-Shift-tab
      Super-p: C-tab

      C-d: delete
      Super-d: C-delete

  - name: Google Search
    application:
      only: Google-chrome
    remap:
      Super-s: C-f
      C-g: Esc
      C-s: C-g
      Super-Enter: C-Enter

  - name: Slack
    application:
      only: Slack
    remap:
      Super-k: C-k
      C-M-k: Shift-Alt-up
      C-M-j: Shift-Alt-down
      C-Super-m: C-Enter

      Super-1: C-1
      Super-2: C-2
      Super-3: C-3
      Super-4: C-4
      Super-5: C-5
      Super-6: C-6
      Super-7: C-7
      Super-8: C-8
      Super-9: C-9
