- name: Check font
  shell: "fc-match {{ item.font }}"
  register: check_font
  changed_when: check_font.stdout.find(item.font) == -1
  with_items:
    - "{{ fonts }}"

- name: フォントディレクトリ作成
  become: true
  file:
    path: "{{ item.font_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ fonts }}"
  register: create_font_directory
  when: check_font.changed

- name: フォントファイル展開
  become: true
  unarchive:
    remote_src: true
    src: "{{ item.url }}"
    dest: "{{ item.font_dir }}"
  with_items:
    - "{{ fonts }}"
  when: check_font.changed

- name: フォントキャッシュ更新
  shell: fc-cache -vf
  changed_when: false
