- name: Clone fzf
  git:
    repo: "{{ fzf.git_url }}"
    dest: "{{ fzf.install_dir }}"
    depth: 1
  register: clone_fzf
- name: Init fzf
  shell: ~/.local/share/fzf/install --xdg --completion --key-bindings  --no-update-rc --no-bash --no-fish
  when: clone_fzf.changed
