#!/bin/zsh
# plugin
zinit wait lucid blockf light-mode for \
    @'zsh-users/zsh-autosuggestions' \
    @'zsh-users/zsh-completions' \
    @'zsh-users/zsh-syntax-highlighting' \
    @'olets/zsh-abbr' \
    @'b4b4r07/enhancd'

# Alias
setopt complete_aliases

case "${PLATFORM}" in
    osx)
        (( ${+commands[gdate]} )) && alias date='gdate'
        (( ${+commands[gls]} )) && alias ls='gls'
        (( ${+commands[gmkdir]} )) && alias mkdir='gmkdir'
        (( ${+commands[gcp]} )) && alias cp='gcp'
        (( ${+commands[gmv]} )) && alias mv='gmv'
        (( ${+commands[grm]} )) && alias rm='grm'
        (( ${+commands[gdu]} )) && alias du='gdu'
        (( ${+commands[ghead]} )) && alias head='ghead'
        (( ${+commands[gtail]} )) && alias tail='gtail'
        (( ${+commands[gawk]} )) && alias awk='gawk'
        (( ${+commands[gsed]} )) && alias sed='gsed'
        (( ${+commands[ggrep]} )) && alias grep='ggrep'
        (( ${+commands[gfind]} )) && alias find='gfind'
        (( ${+commands[gdirname]} )) && alias dirname='gdirname'
        (( ${+commands[gxargs]} )) && alias xargs='gxargs'
        alias ssh="~/.ssh/bin/ssh_change.sh"
        ;;
    linux)
        alias open="xdg-open"
        ;;
esac

alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'
alias sudo='TERM=xterm-256color sudo'
alias grep="grep --color=auto"
alias emacs="emacs -nw"
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

if [ -e "$NVM_DIR/nvm.sh" ]; then
    alias nvm='unalias nvm node npm && . "$NVM_DIR"/nvm.sh && nvm'
    alias node='unalias nvm node npm && . "$NVM_DIR"/nvm.sh && node'
    alias npm='unalias nvm node npm && . "$NVM_DIR"/nvm.sh && npm'
fi


# Ls colors
export LS_COLORS='di=34:ln=35:so=32:pi=33:ex=31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'
zstyle ':completion:*' list-colors "${LS_COLORS}"

if type lsd > /dev/null 2>&1; then
    alias ls='lsd'
else
    alias ls='ls --color=auto'
fi

alias jl='~/.local/bin/jupyterlab.sh'
alias ta='~/.local/bin/tmux_session.sh'

chpwd() {
    ls
}

# Emacs tramp config for zsh
if [[ "$TERM" == "dumb" ]]; then
    unsetopt zle
    unsetopt prompt_cr
    unsetopt prompt_subst
    unfunction precmd
    unfunction preexec
    PS1='$ '
fi

# Google Cloud SDK.
if [ -f "/usr/share/google-cloud-sdk/completion.zsh.inc" ]; then . "/usr/share/google-cloud-sdk/completion.zsh.inc"; fi

# config edit command
get_config_file() {
  local file
  file=$(
         rg --files --hidden --follow --glob "!**/.git/*" "$HOME/.config" | fzf-tmux -p 80% \
             --preview 'bat  --color=always --style=header,grid {}' --preview-window=right:60%
     ) 
  printf "$file"
}
ec() {
  local file="$(get_config_file)"
  if [ -n "${file}" ]; then
      emacs "$file"
  fi
}

vc() {
  local file="$(get_config_file)"
  if [ -n  "${file}" ]; then
      vim "$file"
  fi
}

# Completion
fpath+=$ZSH_COMPLETION_DIR
autoload -Uz compinit && compinit

# Navi
(( ${+commands[navi]} )) &&  eval "$(navi widget zsh)"
