# cache-dir
cache-dir = "~/.cache/ruff"

# Enable rules.
# https://beta.ruff.rs/docs/rules/
#select = ["E", "W", "F", "B", "I", "RUF", "NPY", "TRY", "PLW", "PLR", "PLE", "PL", "PD", "PTH", "ARG", "SIM"]
select = ["ALL"]
ignore = ["E501", "PGH", "DJ", "D", "T20", "ERA", "C90", "ANN101"]

fixable = ["I", "SIM118"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
