- name: Make git config directory
  file:
    path: ~/.config/git
    state: directory

- name: Link .ignore
  file:
    src: "{{ role_path }}/files/ignore"
    dest: ~/.config/git/ignore
    state: link
