- name: Link .gitignore_global
  file:
    src: "{{ role_path }}/files/.gitignore_global"
    dest: ~/.gitignore_global
    state: link
  
- name: Check git global settings
  shell: bash -lc " git config --list --global | grep .gitignore_global"
  register: gitignore_global
  ignore_errors: true
  changed_when: false

- name: Init git
  shell: git config --global core.excludesfile ~/.gitignore_global
  when: gitignore_global is failed
