- import_playbook: pre-common.yml

- hosts: localhost
  connection: local
  roles:
    - apt_common
    - apt_gui
    - font
    - gnome
    - skk
    - gogh
    - xkeysnail

- import_playbook: post-common.yml
