- name: Make config dir
  file:
    path: ~/Library/ApplicationSupport/AquaSKK
    state: directory

- name: Link config
  file:
    src: "{{ role_path }}/files/keymap.conf"
    dest: ~/Library/ApplicationSupport/AquaSKK/keymap.conf
    state: link
