- name: Make config dir
  file:
    path: "~/Library/Application Support/AquaSKK"
    state: directory

- name: Link config
  file:
    src: "{{ role_path }}/files/keymap.conf"
    dest: "~/Library/Application Support/AquaSKK/keymap.conf"
    state: link
