- name: Make karabiner config directory
  file:
    path: ~/.config/karabiner
    state: directory

  - name: Link karabiner.json
  file:
    src: "{{ role_path }}/files/karabiner.json"
    dest: ~/.config/karabiner/karabiner.json
    state: link
