- name: Link .zshenv
  file:
    src: "{{ role_path }}/files/zsh/.zshenv"
    dest: ~/.zshenv
    state: link

- name: Link zsh config
  file:
    src: "{{ role_path }}/files/zsh"
    dest: ~/.config/zsh
    state: link

- name: Make completion directory
  file:
    path: ~/.local/share/zsh/completion
    state: directory

- name: Make history directory
  file:
    path: ~/.local/state/zsh
    state: directory

- name: Import zinit
  import_tasks: zinit.yml
