#!/usr/bin/env bash

set -euo pipefail

repo_dir="${TARGET_REPO_DIR:-${REPO_DIR:-}}"
if [ -z "$repo_dir" ]; then
    repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

# shellcheck source=/dev/null
. "${repo_dir}/scripts/common.sh"

config_file="${repo_dir}/.pre-commit-config.yaml"
hook_file="$(git -C "$repo_dir" rev-parse --git-path hooks/pre-commit 2>/dev/null || true)"

title "Install/Update git hooks"

if ! git -C "$repo_dir" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    info "Skip git hook install: ${repo_dir} is not a git repository."
    exit 0
fi

if [ ! -f "$config_file" ]; then
    info "Skip git hook install: ${config_file} was not found."
    exit 0
fi

if ! command -v prek >/dev/null 2>&1; then
    warning "Skip git hook install: prek is not available in PATH."
    exit 0
fi

prek_version="$(prek --version 2>/dev/null | awk '{print $2}')"

if [ -n "$hook_file" ] && [ -f "$hook_file" ] \
    && grep -Fq "File generated by prek" "$hook_file" \
    && grep -Fq -- "--script-version 4" "$hook_file" \
    && [ -n "$prek_version" ] \
    && grep -Fq "prek-${prek_version}/bin/prek" "$hook_file"; then
    info "Git hooks are already up to date."
    exit 0
fi

(
    cd "$repo_dir"
    prek install
)

success "Git hooks are up to date."
