#!/usr/bin/env bash

app_id=$( swaymsg -t get_tree | jq -r '.. | select(.type?) | select(.focused==true) | .window_properties.class'  )
if [[ $app_id != "Enpass" ]]; then
    # --no-persist so that we preserve rich text:
    clipman store --no-persist
fi
