tap "homebrew/cask-fonts"
brew "curl"
brew "coreutils"
brew "findutils"
brew "gnu-sed"
brew "grep"
brew "htop"
brew "duf"
brew "tree"
brew "gnupg"
brew "pinentry-mac"
brew "cmigemo"
brew "less"
brew "nkf"
brew "rsync"
brew "openssl"
brew "readline" # python dependencies
brew "sqlite3"  # python dependencies
brew "xz"       # python dependencies
brew "zlib"     # python dependencies
brew "tcl-tk"   # python dependencies
brew "python3"
brew "pipx"
brew "trash-cli"
brew "git"
brew "neofetch"
brew "axel"
brew "jq"
brew "mas"
brew "ncurses" # for tmux-256color
brew "tmux"
brew "vim"
brew "wget"
brew "bash"
brew "zsh"
brew "iproute2mac"
brew "go"
brew "hugo"
brew "cmake"
brew "pam-reattach" # for TouchID with sudo
brew "unar"
brew "shellcheck"
cask "wezterm"
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"
cask "monitorcontrol"
cask "alfred"
cask "discord"
cask "notion"
cask "zoom"
cask "firefox"
cask "vivaldi"
cask "google-chrome"
cask "google-drive"
cask "vlc"
cask "zotero"
cask "tunnelblick"
cask "stats"
cask "anki"
cask "font-cica"
cask "font-plemol-jp"
cask "appcleaner"
cask "aquaskk"
cask "karabiner-elements"
cask "nextcloud"
cask "libreoffice"
mas "Kindle", id: 302584613
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Sequel Ace", id: 1518036000
mas "GoodNotes", id: 1444383602
mas "Dictonaries", id: 1380563956
mas "MeetingBar", id: 1532419400
mas "WireGuard", id: 1451685025
mas "Bitwarden", id: 1352778147
