tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
brew "curl"
brew "coreutils"
brew "findutils"
brew "gnu-sed"
brew "grep"
brew "duf"
brew "tree"
brew "gnupg"
brew "pinentry-mac"
brew "cmigemo"
brew "less"
brew "nkf"
brew "rsync"
brew "openssl"
brew "readline" # python dependencies
brew "sqlite3"  # python dependencies
brew "xz"       # python dependencies
brew "zlib"     # python dependencies
brew "tcl-tk"   # python dependencied
brew "trash-cli"
brew "git"
brew "neofetch"
brew "axel"
brew "jq"
brew "mas"
brew "tmux"
brew "vim"
brew "wget"
brew "bash"
brew "zsh"
brew "python3"
brew "pipx"
brew "go"
brew "hugo"
brew "cmake"
brew "shellcheck"
brew "isync"
brew "mu"
brew "terminal-notifier"
tap "wez/wezterm"
cask "wez/wezterm/wezterm"
tap "d12frosted/emacs-plus"
brew "emacs-plus@28", args: ["with-native-comp"]
tap "koekeishiya/formulae"
brew "yabai"
brew "skhd"
cask "monitorcontrol"
cask "alfred"
cask "discord"
cask "notion"
cask "zoom"
cask "vivaldi"
cask "google-chrome"
cask "google-drive"
cask "vlc"
cask "stats"
cask "anki"
cask "font-cica"
cask "appcleaner"
cask "aquaskk"
cask "karabiner-elements"
cask "tunnelblick"
cask "nextcloud"
mas "Kindle", id: 405399194
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Enpass", id: 732710998
mas "Sequel Ace", id: 1518036000
mas "GoodNotes", id: 1444383602
mas "Dictonaries", id: 1380563956
mas "MeetingBar", id: 1532419400
mas "WireGuard", id: 1451685025
